version: "3.7"

services:

  django_v2:
    build: ./cyberclassroom
    container_name: django_v2
    restart: always
    command: uwsgi /app/uwsgi.ini
    volumes:
      - ./cyberclassroom:/app
    expose:
      - "8080"
    env_file:
      - ./cyberclassroom/.env
    environment:
      - DEBUG=True
      - TZ=Asia/Bangkok
    networks:
      - classroom_net

networks:
  classroom_net:
    external: true
