# Generated by Django 3.0.7 on 2020-06-19 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_auto_20200619_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='created_at',
            field=models.CharField(default=datetime.datetime(2020, 6, 19, 13, 7, 39, 992110), max_length=50),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='updated_at',
            field=models.CharField(max_length=50),
        ),
    ]
