# Generated by Django 3.0.7 on 2020-06-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20200619_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='added_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='created_at',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='updated_at',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
