# Generated by Django 3.0.7 on 2020-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_auto_20200619_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='id',
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ชื่อห้อง'),
        ),
    ]
