# Generated by Django 3.0.7 on 2020-06-19 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_auto_20200619_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassScheduleCenter',
            fields=[
                ('course_no', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='รหัสวิชา')),
                ('course_name_thai', models.CharField(max_length=50, verbose_name='ชื่อวิชา TH')),
                ('course_name_eng', models.CharField(max_length=50, verbose_name='ชื่อวิชา EN')),
                ('instructor', models.CharField(max_length=200, verbose_name='อาจารย์ผู้สอน')),
                ('course_day', models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=20, verbose_name='วันที่เรียน')),
                ('time_start', models.CharField(max_length=20, verbose_name='เริ่มเรียน (00:00)')),
                ('time_end', models.CharField(max_length=20, verbose_name='สิ้นสุด (00:00)')),
                ('added_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.CharField(blank=True, max_length=50)),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live.Classrooms')),
            ],
        ),
    ]
