# Generated by Django 3.0.7 on 2020-06-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0006_classschedulecenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday')], default='Monday', max_length=20, verbose_name='วันที่เรียน'),
        ),
    ]
