# Generated by Django 3.0.7 on 2020-06-24 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0008_auto_20200619_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='room_status',
            field=models.CharField(choices=[('เปิด', '1'), ('ปิด', '0')], default='เปิด', max_length=20, verbose_name='สถานะห้องเรียน'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_no',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live.Classrooms', verbose_name='ห้องเรียน'),
        ),
    ]
