# Generated by Django 3.0.7 on 2020-06-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0009_auto_20200624_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='room_status',
            field=models.CharField(choices=[('1', 'เปิด'), ('0', 'ปิด')], default='1', max_length=20, verbose_name='สถานะห้องเรียน'),
        ),
    ]
