# Generated by Django 3.0.7 on 2020-06-29 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0011_auto_20200629_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='room_location',
            new_name='room_location_id',
        ),
    ]
