# Generated by Django 3.0.7 on 2020-06-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0012_auto_20200629_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classrooms',
            old_name='room_location_id',
            new_name='room_location',
        ),
    ]
