# Generated by Django 3.0.7 on 2020-06-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0014_auto_20200629_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='room_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='live.Locations', verbose_name='เรียนที่'),
        ),
    ]
