# Generated by Django 3.0.7 on 2020-07-03 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0015_auto_20200629_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classrooms',
            options={'verbose_name': 'รายการห้องเรียน', 'verbose_name_plural': 'ข้อมูลห้องเรียน'},
        ),
        migrations.AlterModelOptions(
            name='classschedulecenter',
            options={'verbose_name': 'รายการวิชาเรียน', 'verbose_name_plural': 'ข้อมูลวิชาเรียน'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'รายการตำแหน่งห้องเรียน', 'verbose_name_plural': 'ข้อมูลตำแหน่งห้องเรียน'},
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live.Classrooms', verbose_name='ห้องเรียน'),
        ),
    ]
