# Generated by Django 3.0.7 on 2020-07-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0017_auto_20200703_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'managed': False, 'verbose_name': 'รายการตำแหน่งห้องเรียน', 'verbose_name_plural': 'ข้อมูลตำแหน่งห้องเรียน'},
        ),
    ]
