# Generated by Django 3.0.7 on 2020-07-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0018_auto_20200703_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'รายการตำแหน่งห้องเรียน', 'verbose_name_plural': 'ข้อมูลตำแหน่งห้องเรียน'},
        ),
        migrations.CreateModel(
            name='LogSubjectInRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=7, verbose_name='รหัสวิชา')),
                ('created_at', models.CharField(blank=True, max_length=50)),
                ('room_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live.Locations', verbose_name='เรียนที่')),
            ],
        ),
    ]
