# Generated by Django 3.0.7 on 2020-07-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0020_logsubjectinroom_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='รหัสวิชา'),
        ),
    ]
