# Generated by Django 3.0.7 on 2020-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0021_auto_20200730_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_name_eng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อวิชา EN'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_name_thai',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อวิชา TH'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='instructor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='อาจารย์ผู้สอน'),
        ),
    ]
