# Generated by Django 3.0.7 on 2026-05-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0024_auto_20200730_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('room_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sessions_cupertino', models.CharField(max_length=5)),
                ('sessions_total', models.CharField(max_length=5)),
                ('updated', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'live_count',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiveClassroom',
            fields=[
                ('room_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('room_stream', models.CharField(max_length=200)),
                ('room_order', models.IntegerField()),
                ('room_status', models.CharField(max_length=20)),
                ('updated_at', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'live_classrooms',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='classschedulecenter',
            options={'ordering': ('time_start',), 'verbose_name': 'รายการวิชาเรียน', 'verbose_name_plural': 'ข้อมูลวิชาเรียน'},
        ),
        # chat_pin มีอยู่ใน DB แล้ว (เพิ่มไปก่อน migration) — ข้ามด้วย SeparateDatabaseAndState
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='classrooms',
                    name='chat_pin',
                    field=models.CharField(blank=True, default='', help_text='ตั้งรหัสลับให้อาจารย์พิมพ์เพื่อแสดง badge "อาจารย์" ในแชท (ว่างเปล่า = ไม่เปิดฟีเจอร์นี้)', max_length=20, verbose_name='รหัสอาจารย์ (Chat PIN)'),
                ),
            ],
            database_operations=[],  # ไม่ต้อง ALTER TABLE เพราะ column มีอยู่แล้ว
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], default='Monday', max_length=20, verbose_name='วันที่เรียน'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_no',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='logsubjectinroom',
            name='course_no',
            field=models.CharField(max_length=30, verbose_name='รหัสวิชา'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=80, verbose_name='ชื่อผู้ส่ง')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='อาจารย์')),
                ('message', models.TextField(max_length=500, verbose_name='ข้อความ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='live.Classrooms', verbose_name='ห้องเรียน')),
            ],
            options={
                'verbose_name': 'ข้อความแชท',
                'verbose_name_plural': 'ข้อความแชทในห้องเรียน',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'created_at'], name='live_chatme_room_id_925390_idx'),
        ),
    ]
