# Generated by Django 3.0.7 on 2026-05-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0026_chatmessage_sender_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='active_course',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='วิชาที่กำลังสอน'),
        ),
    ]
