# Generated by Django 3.0.7 on 2026-06-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0030_holidaydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='room_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=500, verbose_name='ข้อความ (แสดงผล)'),
        ),
    ]
