# Generated by Django 3.0.7 on 2026-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0035_class_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_no',
            field=models.CharField(max_length=100, verbose_name='รหัสวิชา'),
        ),
        migrations.AlterField(
            model_name='holidaydate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ชื่อ / หัวข้อ'),
        ),
    ]
