# Generated by Django 3.0.7 on 2026-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0036_auto_20260618_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_name_eng',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='ชื่อวิชา EN'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_name_thai',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='ชื่อวิชา TH'),
        ),
    ]
