# Generated by Django 3.0.7 on 2026-06-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0037_auto_20260618_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='instructor',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='อาจารย์ผู้สอน'),
        ),
    ]
