[uwsgi]
socket = :8080
#http = 0.0.0.0:8000
chdir = /Users/a0002/Desktop/docker-classroom/cyberclassroom
home = /Users/a0002/Desktop/docker-classroom/cyberclassroom/env
wsgi-file = /Users/a0002/Desktop/docker-classroom/cyberclassroom/wsgi.py
# chdir = /app/cyberclassroom
# home = /app/env
# wsgi-file = /app/cyberclassroom/wsgi.py
module = cyberclassroom.wsgi:application
#env = DJANGO_SETTINGS_MODULE=cyberclassroom.settings
master = true
processes = 4
threads = 2