worker_processes auto;

events {
    worker_connections 8192;
    multi_accept on;
}

http {
    limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/m;
    limit_req_zone $binary_remote_addr zone=search_limit:10m rate=10r/m;

    client_max_body_size 10M;
    uwsgi_buffers 8 16k;
    uwsgi_buffer_size 32k;

    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    resolver 127.0.0.11 valid=30s;   # Docker internal DNS

    include /etc/nginx/conf.d/*.conf;
}
