# nginx/default.conf
# (limit_req_zone ย้ายไปไว้ใน nginx.conf แล้ว เพื่อป้องกัน duplicate)

server {
    listen 80;

    # ❌ บล็อก IP ที่ยิงหนัก
    deny 52.167.144.0/24;
    deny 40.77.167.0/24;
    deny 40.76.0.0/15;
    deny 13.66.0.0/16;

    # ✅ ปล่อย IP อื่นใช้งานได้
    allow all;

    location /searchRoom {
        # limit_req zone=search_limit burst=5 nodelay;
        if ($http_user_agent ~* "(bingbot|curl|python|requests|wget|scrapy|bot|spider|crawl)") {
            return 444;
        }
        # ถ้าไม่ใช่ bot ให้ส่งต่อไปยัง uwsgi
        # include uwsgi_params;
        # uwsgi_pass django:8080;
        proxy_pass http://django_v2:8080/searchRoom;  # ✅ เพิ่ม /searchRoom ด้านหลังด้วย
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location = /robots.txt {
        alias /var/www/static/robots.txt;
        access_log off;
        log_not_found off;
    }
    location / {
        proxy_pass http://django_v2:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Static files
    location /static/ {
        alias /var/www/static/;
        expires 0;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
