# nginx/default.conf

server {
    # listen 80;
    listen 8849;
    deny 52.167.144.0/24;
    deny 40.77.167.0/24;
    deny 40.76.0.0/15;
    deny 13.66.0.0/16;

    allow all;

    location /searchRoom {
        if ($http_user_agent ~* "(bingbot|curl|python|requests|wget|scrapy|bot|spider|crawl)") {
            return 444;
        }
        proxy_pass http://django_v2:8080/searchRoom;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $real_client_ip;        # ← แก้
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /robots.txt {
        alias /var/www/static/robots.txt;
        access_log off;
        log_not_found off;
    }

    location = /monitor-sse/ {
        proxy_pass              http://django_v2:8080;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $real_client_ip;  # ← แก้
        proxy_read_timeout      120s;
        proxy_buffering         off;
        proxy_cache             off;
        proxy_set_header        Connection '';
        proxy_http_version      1.1;
        chunked_transfer_encoding on;
    }

    location / {
        proxy_pass http://django_v2:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $real_client_ip;        # ← แก้
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static/ {
        alias /var/www/static/;
        expires 0;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}