# Generated by Django 3.0.7 on 2020-06-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='room_location',
            field=models.CharField(max_length=50, verbose_name='เรียนที่'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room_name',
            field=models.CharField(max_length=50, verbose_name='ชื่อห้อง'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room_stream',
            field=models.CharField(max_length=200, verbose_name='ชื่อช่องในการถ่ายทอด'),
        ),
    ]
