# Generated by Django 3.0.7 on 2020-06-19 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0007_auto_20200619_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live.Classrooms', verbose_name='the related poll'),
        ),
    ]
