# Generated by Django 3.0.7 on 2020-06-29 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0010_auto_20200624_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50, verbose_name='ชื่อสถานที่')),
            ],
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday')], default='Monday', max_length=20, verbose_name='วันที่เรียน'),
        ),
        migrations.AlterField(
            model_name='classschedulecenter',
            name='room_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='live.Classrooms', verbose_name='ห้องเรียน'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='live.Locations', verbose_name='เรียนที่'),
        ),
    ]
