# Generated by Django 3.0.7 on 2020-07-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0016_auto_20200703_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='room_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='live.Locations', verbose_name='เรียนที่'),
        ),
    ]
