# Generated by Django 3.0.7 on 2020-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0019_auto_20200703_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsubjectinroom',
            name='user_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
