# Generated by Django 3.0.7 on 2020-07-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0023_auto_20200730_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedulecenter',
            name='course_day',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], default='Monday', max_length=20, verbose_name='วันที่เรียน'),
        ),
    ]
