# upstream django {
#     # server unix:///path/to/your/mysite/mysite.sock; # for a file socket
#     server 127.0.0.1:8080; # for a web port socket (we'll use this first)
# }

# server {

#     listen 80;

#     location / {
#         include uwsgi_params;
#         uwsgi_pass django:8080;
#     }
#     location /static {
#         alias /var/www/static;
#     }

# }
# เพิ่มที่ระดับ http (ด้านบนสุดของ nginx.conf)
limit_req_zone $binary_remote_addr zone=search_limit:10m rate=10r/m;

server {
    listen 80;

    # ✅ จำกัด /searchRoom
    location /searchRoom {
        return 444;  # nginx จะ "ปิดการเชื่อมต่อทันที" โดยไม่ตอบอะไร
        # return 403;  # ปิดการเข้าถึงทั้งหมด
        # Block bot by User-Agent
        # if ($http_user_agent ~* "bingbot|python-requests|scrapy|curl") {
        #     return 403;
        # }
        # limit_req zone=search_limit burst=5 nodelay;
        # include uwsgi_params;
        # uwsgi_pass django:8080;
    }

    # ✅ ปล่อย path อื่นตามเดิม
    location / {
        include uwsgi_params;
        uwsgi_pass django:8080;
    }

    # ✅ static files
    location /static {
        alias /var/www/static;
    }
}
