# nginx/nginx.conf
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # สร้างโซนเก็บสถานะ rate limit ของแต่ละ client IP
    # ✅ ใส่ limit_req_zone ทั้งหมดที่นี่ ไม่ซ้ำกัน
    limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/m;
    # limit_req_zone $binary_remote_addr zone=search_limit:10m rate=10r/m;
    # ✅ เพิ่มการตั้งค่า buffer และขนาดไฟล์
    client_max_body_size 10M;
    uwsgi_buffers 8 16k;
    uwsgi_buffer_size 32k;

    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;
}
