[uwsgi]
http = :8000
# socket = :8080
# chdir = /Users/a0002/Desktop/docker-classroom/cyberclassroom
# home = /Users/a0002/Desktop/docker-classroom/env
#chdir = /Users/a0002/Desktop/docker-classroom/django
#home = /app/env
#venv= /Users/a0002/Desktop/docker-classroom/django/env
#wsgi-file = /app/test.py
# wsgi-file = /app/cyberclassroom/wsgi.py
#env = DJANGO_SETTINGS_MODULE=cyberclassroom.settings
module = webapp.wsgi
master = true
processes = 4
threads = 2